/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 diamond.gltf
Author: Karolina Renkiewicz (https://sketchfab.com/KarolinaRenkiewicz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/diamond-1ab1e8de5a604b4081c15326eaa5682b
Title: Diamond
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Diamond(props) {
  const { nodes, materials } = useGLTF('./MODELS/diamond.gltf'); 




  return (
    <group  {...props} dispose={null} >
      <mesh geometry={nodes.pCone1_DiamondOutside_0.geometry} material={materials.DiamondOutside} />
    </group>
  )
}

useGLTF.preload('./MODELS/diamond.gltf')
